### ISSUE TITLE
Display latest data upload on Sonde dashboard card

### ISSUE THREAD

**Issue by Caesarh97** [aqualinkorg/aqualink-app#1020]
When uploading water quality data for the Sonde dashboard card, the oldest data upload is showing. We should display the latest data point in the dashboard card. In [https://aqualink.org/sites/2188](https://aqualink.org/sites/2188), for example, the data upload with the data from 2022 is appearing. I’ve uploaded data in another upload that has data points from 2024. The most recent data points should populate the dashboard card. 

<img width="1328" alt="Screenshot 2024-09-13 at 12 00 15 PM" src="https://github.com/user-attachments/assets/db2bb2ca-af5e-485d-8544-f6bd80317334">

**Comment by yaodingyd** [comment]
not sure why but this issue has no payout...

**Comment by ericboucher** [comment]
@yaodingyd not sure what's happening but I can't issue the payout for that one. Can you try to claim it again?

**Comment by yaodingyd** [comment]
most likely a bug from algora side that one PR can't claim two issues. I'll report this to them

**Comment by ericboucher** [comment]
Let me know how it goes. Alternatively I can give you a bigger tip on the next bounty and close that one ;)

**Comment by algora-pbc** [comment]
Hey @yaodingyd, thanks for flagging this. It can now be paid out from your dashboard @ericboucher
