### ISSUE TITLE
Change HUI measurement for salinity to ppt

### ISSUE THREAD

**Issue by Caesarh97** [aqualinkorg/aqualink-app#1047]
Hello, 
Here's a short and fast issue. Could we please change the measurement for HUI data from psu to ppt for salinity? 

ppt is the correct measurement, and you should add it all in lowercase "ppt". 

I can see the measurements in two places on the dashboard. 

<img width="326" alt="Screenshot 2024-10-25 at 12 01 56 PM" src="https://github.com/user-attachments/assets/44e2517e-92e6-4980-98d2-1e9e38de2938">
<img width="312" alt="Screenshot 2024-10-25 at 12 02 05 PM" src="https://github.com/user-attachments/assets/eee53dda-b2f5-45e5-9195-289db03e44f7">

**Comment by ericboucher** [comment]
@Caesarh97 This is actually not trivial because the first salinity data we had in our database (Vesta) was in psu. But it looks like psu ~ ppt so maybe it's not that big of a deal?

**Comment by Caesarh97** [comment]
@ericboucher Okay, thanks for letting me know! For Sonde data, we want to keep the psu, but for HUI data, we want to use ppt. I checked, and all Sonde uploads that I know of has psu, but that's a completely different measurement than what HUI are measuring (like measuring temperature in F when it's actually C). Would it be possible to do it differently for HUI data? It looks like we're uploading salinity differently on the Sonde upload compared to HUI. HUI upload shows the salinity column as "Salinity", and Sonde shows the salinity column as "Sal psu". Would it maybe be possible to make two salinity metrics? One salinity ppt and one salinity psu? Is it the column headers that decide which graphs that are being populated?
