### ISSUE TITLE
Search reef by name alignment is wrong

### ISSUE THREAD

**Issue by peterive** [aqualinkorg/aqualink-app#116]
It should either be left aligned or aligned with the left hand border of the table

**Comment by ericboucher** [comment]
Current implementation:

<img width="1680" alt="Screen Shot 2020-09-04 at 7 04 11 PM" src="https://user-images.githubusercontent.com/16843267/92326961-632d7a80-f056-11ea-9cd0-f461fa7751ab.png">

**Comment by ewolfer67** [comment]
I would align the search box with the "Featured" reef title if possible.
Also, would it be possible to increase the gap between the map and the right content? Maybe triple the current gutter?

**Comment by ericboucher** [comment]
Can you post a screenshot of what you have in mind for the gutter?

**Comment by ericboucher** [comment]
Gutter should be aroun 40px, see initial designs below:

<img width="992" alt="Screen Shot 2020-09-07 at 10 12 16 AM" src="https://user-images.githubusercontent.com/16843267/92364258-1ba8fc00-f0f3-11ea-84f8-2771d648fd7c.png">
