### ISSUE TITLE
Account/profile icon in top right does nothing

### ISSUE THREAD

**Issue by peterive** [aqualinkorg/aqualink-app#118]
The empty profile icon does nothing at this point. Maybe we should remove it for now?

**Comment by ewolfer67** [comment]
Remove it.

**Comment by ericboucher** [comment]
@ewolfe we still need to show "something" when users are logged in. Should we show the user name instead?

**Comment by ericboucher** [comment]
<img width="202" alt="Screen Shot 2020-09-04 at 7 55 23 PM" src="https://user-images.githubusercontent.com/16843267/92271951-f8126580-eee8-11ea-8783-6d1d100deed0.png">

**Comment by ericboucher** [comment]
@ewolfer67 how does that look? ^

**Comment by ewolfer67** [comment]
Perfect for now.
