### ISSUE TITLE
Sensor and satellite observation stat boxes text is not aligned

### ISSUE THREAD

**Issue by peterive** [aqualinkorg/aqualink-app#122]
![Capture](https://user-images.githubusercontent.com/4451371/92156967-98c82e80-edde-11ea-9f25-006e41736421.JPG)
See image. Also another instance of degree C not being the right font.

**Comment by ericboucher** [comment]
- move the no spotter alert to the bottom of the sensor card
- I think we should be able to force the titles to be on one line until we wrap the boxes
