### ISSUE TITLE
Chart legend change

### ISSUE THREAD

**Issue by drewjgray** [aqualinkorg/aqualink-app#129]
<img width="1070" alt="Screen Shot 2020-09-04 at 10 38 54 AM" src="https://user-images.githubusercontent.com/6283065/92270496-046fd180-ee9b-11ea-8c20-74ac3fa10779.png">

The legend feels too much like a chart made in Excel. Can we make the chart labels more like the way the maximum monthly mean is labeled?

**Comment by ericboucher** [comment]
Keeping the default legends like this allows us to have a toggle on/off which will be useful when we have more charts.

**Comment by drewjgray** [comment]
Let's see if we can do better. We do not have functionality that requires switching lines on and off.

**Comment by ewolfer67** [comment]
Since we are only showing the two lines and aren't implementing filtering we can simplify it a little. @drewjgray ?
![image](https://user-images.githubusercontent.com/29734072/92981802-517e1580-f450-11ea-86dd-dbe5008993ba.png)

**Comment by drewjgray** [comment]
Yes we can simplify, but the attached screenshot above has the same legend, just vertical this time. @ewolfer67

**Comment by ericboucher** [comment]
@drewjgray can you share an example of what you would expect?

**Comment by drewjgray** [comment]
If we label the two threshold lines, I think we do get rid of the legend entirely, as it is only one line. We just call the whole chart `Sea Surface Temperature` instead of `Daily Water Temperature`. It will clean things up.
