### ISSUE TITLE
Map is too slow

### ISSUE THREAD

**Issue by drewjgray** [aqualinkorg/aqualink-app#132]
The map should be very easy to move around and zoom in and out. Please fix the performance issues of the map.

**Comment by drewjgray** [comment]
Is this fix deployed on prod? It still feels sluggish for me.

**Comment by ericboucher** [comment]
Interesting thread - https://stackoverflow.com/questions/52620309/constructing-a-lot-of-markers-on-react-leaflet-map-is-too-slow
