### ISSUE TITLE
Initial zoom and make reef detail map moveable

### ISSUE THREAD

**Issue by drewjgray** [aqualinkorg/aqualink-app#133]
Make the initial zoom of the reef detail map 5 zoom levels greater. And allow the map to be able to be moved in addition to allowing zoom functionality.

**Comment by ericboucher** [comment]
@drewjgray can you give a screenshot of how you would like the map to look like?

**Comment by drewjgray** [comment]
Same as current, just zoom level + 5 and draggable == true.

**Comment by ericboucher** [comment]
We decided not to have it draggable in the past, I think it avoids people getting lost. But up to you

**Comment by drewjgray** [comment]
Let's make it draggable.
