### ISSUE TITLE
Direction arrow spacing and sizing is off

### ISSUE THREAD

**Issue by drewjgray** [aqualinkorg/aqualink-app#134]
<img width="128" alt="Screen Shot 2020-09-04 at 10 48 29 AM" src="https://user-images.githubusercontent.com/6283065/92271178-32a1e100-ee9c-11ea-8951-36d456408ad4.png">

**Comment by ericboucher** [comment]
os@drewjgray let me know what you think of the latest version on https://os-aqualink.web.app/reefs/1158
