### ISSUE TITLE
Allow managers to go back to set featured images

### ISSUE THREAD

**Issue by peterive** [aqualinkorg/aqualink-app#171]
Once I've uploaded an image I can't go back and set that image to the featured image from any of the screens

**Comment by ericboucher** [comment]
@peterive for point number one, where would you expect to be able to edit it? do we want to have an edit mode for reef admins?

**Comment by ewolfer67** [comment]
We’re not currently affording the reef manager the ability to fully edit a survey/images right now. The "Survey Detail Page" (if logged in as a Reef Manager) should have the Fav "star" controls displayed in the upper right corner of the image carousels as shown in the page design on Zeplin. 

![Uploading image.png…]()
