### ISSUE TITLE
Add legend to home screen map showing what values the colors represent. 

### ISSUE THREAD

**Issue by drewjgray** [aqualinkorg/aqualink-app#178]
Let's put a simple legend in the bottom corner like this (taken from Windy.com). 
<img width="316" alt="Screen Shot 2020-09-11 at 8 36 53 AM" src="https://user-images.githubusercontent.com/6283065/92945535-40121a80-f40a-11ea-9936-02fe85227465.png">

We need one for SST and one for DHW.

**Comment by ewolfer67** [comment]
@drewjgray Do you mean SST and Heat Stress?

**Comment by drewjgray** [comment]
@ewolfer67 Yes for SST and Heat Stress. 
1. For SST I am awaiting the color/value map back from Sofar. Will update here when I get it. 
2. For Heat Stress, we already have the legend, it is the same color/value map for DHW (on the reef detail page).

**Comment by drewjgray** [comment]
@ewolfer67 Here is the legend for SST. Annoyingly the scale doesn't divide well. If we blend the colors like Windy did in the legend I attached above. We could probably round to then nearest whole number. (in degrees C)

<img width="644" alt="Screen Shot 2020-09-14 at 11 13 37 AM" src="https://user-images.githubusercontent.com/6283065/93122580-98038800-f67b-11ea-962d-ff4468635bcb.png">

**Comment by ewolfer67** [comment]
Sea Surface Temp legends 

![sst_c](https://user-images.githubusercontent.com/29734072/93272651-d0ce5a80-f76a-11ea-8261-558d2f7938c9.png)
![sst_f](https://user-images.githubusercontent.com/29734072/93272652-d0ce5a80-f76a-11ea-8a36-0a8ebf90c21e.png)
