### ISSUE TITLE
Allow super admins to edit reef names

### ISSUE THREAD

**Issue by drewjgray** [aqualinkorg/aqualink-app#179]
<img width="413" alt="Screen Shot 2020-09-11 at 8 41 48 AM" src="https://user-images.githubusercontent.com/6283065/92945813-aa2abf80-f40a-11ea-9a71-a8ac1a7bd3d2.png">

We need to be able to edit reef names to clean up the database. The reef name should not include the word "reef" after it. In addition, we need to be able to edit out descriptions of the reef, as above.

**Comment by ericboucher** [comment]
Let's have a simple "Edit" button on the reef details page for admins

**Comment by ericboucher** [comment]
Quid of depth?

**Comment by ericboucher** [comment]
Update - As a temporary implementation, super admins can use internal.io
