### ISSUE TITLE
Add information to featured image? 

### ISSUE THREAD

**Issue by drewjgray** [aqualinkorg/aqualink-app#184]
<img width="646" alt="Screen Shot 2020-09-11 at 8 58 46 AM" src="https://user-images.githubusercontent.com/6283065/92947825-5a99c300-f40d-11ea-92ad-0ca344c2c4d4.png">

Example above. It isn't quite obvious what that image is doing up there. Maybe we can add some info about the survey data, survey point, featured image heading, etc.

**Comment by drewjgray** [comment]
Any updates here?

**Comment by ewolfer67** [comment]
https://zpl.io/V4pnZkN

@ericboucher

**Comment by ericboucher** [comment]
<img width="478" alt="Screen Shot 2020-10-02 at 10 59 20 AM" src="https://user-images.githubusercontent.com/16843267/94906268-73424980-049e-11eb-8090-cc0ec8538002.png">
