### ISSUE TITLE
After uploading survey, the user should be redirected to the survey detail page of the survey they just uploaded. 

### ISSUE THREAD

**Issue by drewjgray** [aqualinkorg/aqualink-app#204]
Currently you are left looking at a survey upload screen (even though you just uploaded a survey), and the only option is to hit the back button twice to go back to the reef detail page. This feels like you are undoing all your actions. The flow should be:

Add new survey -> upload survey media -> survey detail (of the survey you just uploaded) -> option to navigate back to reef detail page.

**Comment by ericboucher** [comment]
Duplicate
