### ISSUE TITLE
Add Mapbox attribution to the map before we go live. 

### ISSUE THREAD

**Issue by drewjgray** [aqualinkorg/aqualink-app#266]
Docs here: https://docs.mapbox.com/help/how-mapbox-works/attribution/

**Comment by ericboucher** [comment]
Good catch!

Are we good with the current map? I think it's worth looking for one with higher zoom levels. The `disappearing island` effect is a bit weird

**Comment by ericboucher** [comment]
And let's add alert legend

let's have at the very bottom:
- mapbox logo on the left
- mapbox and osm attributions on the right

right above it
- layer legend when needed on the left
- alert level legend on the right, always on

For the alert level, let's create a fancier version of the example below, more similar to the temperature legend
<img width="528" alt="Screen Shot 2020-10-01 at 12 16 35 PM" src="https://user-images.githubusercontent.com/16843267/94797166-09fc0100-03e0-11eb-908f-0d03b49a3b9b.png">

**Comment by ericboucher** [comment]
![legends](https://user-images.githubusercontent.com/16843267/94815523-ebefca00-03fa-11eb-9e88-f84b03bffaab.jpeg)
