### ISSUE TITLE
Bugs on Mobile Version

### ISSUE THREAD

**Issue by SimplyBallistic** [aqualinkorg/aqualink-app#350]
Bugs reported by @ericboucher:
- [x] 1. When you click on a reef on the map and open a new reef page, it very often does not load properly and shows “No data” and stays this way. I investigated a bit and I think that it’s because “loading” is set to false and the mobile processing is too slow to catch the change. If you reload the page it works fine. This is obviously not the expected behavior….

 - [x] 2. If you play around on the map, especially around sites that have overlapping pin and click in the overlapping zone a few times, the app crashes on mobile. I was not able to reproduce on desktop. Might have something to do with the touch on mobile trying to send update requests for two competing markers. I was able to reproduce the bug using the mobile dev test mode on chrome desktop

<details>
  <summary>Stacktrace</summary>
  
  ```javascript
index.js:1 The above error occurred in the <Popup> component:
    in Popup (created by Context.Consumer)
    in ForwardRef(Leaflet(Popup)) (at Popup/index.tsx:32)
    in Popup (created by WithStyles(Popup))
    in WithStyles(Popup) (at Markers/index.tsx:113)
    in Marker (created by Context.Consumer)
    in ForwardRef(Leaflet(Marker)) (at Markers/index.tsx:100)
    in MarkerClusterGroup (created by Context.Consumer)
    in ForwardRef(Leaflet(MarkerClusterGroup)) (at Markers/index.tsx:90)
    in LayerGroup (created by Context.Consumer)
    in ForwardRef(Leaflet(LayerGroup)) (at Markers/index.tsx:89)
    in ReefMarkers (at Map/index.tsx:62)
    in div (created by Map)
    in Map (at Map/index.tsx:50)
    in HomepageMap (created by WithStyles(HomepageMap))
    in WithStyles(HomepageMap) (at HomeMap/index.tsx:39)
    in div (created by ForwardRef(Grid))
    in ForwardRef(Grid) (created by WithStyles(ForwardRef(Grid)))
    in WithStyles(ForwardRef(Grid)) (at HomeMap/index.tsx:38)
    in div (created by ForwardRef(Grid))
    in ForwardRef(Grid) (created by WithStyles(ForwardRef(Grid)))
    in WithStyles(ForwardRef(Grid)) (at HomeMap/index.tsx:37)
    in div (at HomeMap/index.tsx:36)
    in Homepage (created by WithStyles(Homepage))
    in WithStyles(Homepage) (created by Context.Consumer)
    in Route (at App/index.tsx:49)
    in Switch (at App/index.tsx:47)
    in div (at App/index.tsx:45)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App/index.tsx:44)
    in ThemeProvider (at App/index.tsx:43)
    in App (at src/index.tsx:37)
    in Provider (at src/index.tsx:36)
Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
  ```
  
</details>

Screenshots: 

1                                    |  2                                  |  3
:-------------------------:|:-------------------------:|:-------------------------:
![Image from iOS](https://user-images.githubusercontent.com/25571542/97945524-e3185c80-1ddb-11eb-95d0-71b84e640fa0.png)    |  ![Image from iOS (1)](https://user-images.githubusercontent.com/25571542/97945537-ef9cb500-1ddb-11eb-9e8b-b66ba0ff248e.png) | ![Image from iOS](https://user-images.githubusercontent.com/25571542/97945562-07743900-1ddc-11eb-98e2-8dbcf7b0c437.png)

**Comment by tleraj** [comment]
2. This appears to be a `leaflet` issue. I was able to reproduce it by clicking on a marker and immediately zoom out and select another marker multiple times. There is also an open issue on github about this: https://github.com/Leaflet/Leaflet/issues/5035. I opened https://github.com/aqualinkorg/aqualink-app/pull/351 in order to add an error boundary to the app. Should I link it to this issue?

**Comment by SimplyBallistic** [comment]
>     1. This appears to be a `leaflet` issue. I was able to reproduce it by clicking on a marker and immediately zoom out and select another marker multiple times. There is also an open issue on github about this: [Leaflet/Leaflet#5035](https://github.com/Leaflet/Leaflet/issues/5035). I opened #351 in order to add an error boundary to the app. Should I link it to this issue?
Thanks for the insight! Your welcome to link it, if this issue closes I'll just open it again and link the pr to solve 1.

**Comment by tleraj** [comment]
I thought of the following workaround for 1.:

**Comment by tleraj** [comment]
I thought of the following workaround for 1.:
Our `Map` component accepts a `style` prop. We could set
```typescript
<Map
  ...
  style={hasPointerEvents ? {} : { pointerEvents: "none" }}
  ...
>
  ...
</Map>
```
We could use a callback `updateMap` that is fired whenever a user clicks on a marker, defined like this:

```typescript
const updateMap = useCallback(() => {
  setHasPointerEvents(false);
  setTimeout(() => setHasPointerEvents(true), 2 * 1000);
}, []);
```

In other words: When a user clicks on a marker, we disable all the pointer events on the map for 2 seconds (or any other timeout) so that he cannot do nothing else than wait for the map to center around that reef. It seems to work fine for desktop, but not for mobile. Just wanted to share my thought :)
