### ISSUE TITLE
Firebase API Key doesn't appear to be optional

### ISSUE THREAD

**Issue by spiderkeys** [aqualinkorg/aqualink-app#370]
In the website package's README.md, it mentions that the REACT_APP_FIREBASE_API_KEY is optional. However, after running the app with `yarn start` with only the REACT_APP_API_BASE_URL variable specified, the page throws an uncaught exception when opened in the browser to the effect of:

```
{code: "auth/invalid-api-key", message: "Your API key is invalid, please check you have copied it correctly.", a: null}
```
from:
```
Provider.getImmediate | @ | provider.ts:108
FirebaseAppImpl._getService | @ | firebaseApp.ts:127
```
After setting up Firebase, creating an API key, and setting the variable, the page correctly loaded in the browser.

**Comment by ericboucher** [comment]
Nice catch @spiderkeys! I think we should aim for the development to work without `REACT_APP_FIREBASE_API_KEY` to make it as easy as possible to interact with the app.

We could also specify a default `REACT_APP_API_BASE_URL` directly in the README or the sample .env. @spiderkeys which BASE_URL did you end up using?

**Comment by spiderkeys** [comment]
@ericboucher I just used localhost as the BASE_URL, as suggested in the current README:
```
Required
   REACT_APP_API_BASE_URL="http://localhost:8080/"
```
This seems like a sane default to me, as many people are going to want to test locally. 

I agree that being able to run the site without a Firebase backend available is a good idea. For reference, my steps right now to bring up the site in a functional manner locally are:
```
cd packages/website
REACT_APP_API_BASE_URL="http://localhost:8080/" REACT_APP_FIREBASE_API_KEY="${FIREBASE_API_KEY}" yarn start
```
