### ISSUE TITLE
Question about the 'packages/application' directory

### ISSUE THREAD

**Issue by spiderkeys** [aqualinkorg/aqualink-app#374]
Looking at the contents and git history of this directory and the 'packages/website' directory, it seems that the 'application' dir is potentially a leftover from initial project setup. Commits to this dir stop on 9/9/2020 and then commits to website begin on the same date. Perhaps this can be removed?

It also seems to immediately redirect to the aqualink website when run, due to:
```typescript
<Route
  exact
  path="/"
  component={() => {
    window.location.replace("https://www.aqualink.org/");
    return null;
  }}
/>
```

**Comment by ericboucher** [comment]
It is actually still in use but only accessible with a strong URL formatting. You can see what it looks like here https://join.aqualink.org/1/not-a-real-token, though it is indeed being phased out now that all the application process can happen from within the app directly.

**Comment by spiderkeys** [comment]
Gotcha, thanks for the clarification!
