### ISSUE TITLE
Implement a better "Route not found"

### ISSUE THREAD

**Issue by ericboucher** [aqualinkorg/aqualink-app#380]
Let's implement better handling of 404. Currently, we get to a default blank page:

<img width="1157" alt="Screen Shot 2020-12-03 at 11 23 14 PM" src="https://user-images.githubusercontent.com/16843267/101134068-ab5d2a00-35be-11eb-94f4-4fcab03ab4f2.png">

**Comment by khattakdev** [comment]
@ericboucher I'll take this

**Comment by ericboucher** [comment]
@ewolfer67 any ideas?

**Comment by khattakdev** [comment]
@ewolfer67  Can you please share the assets?

**Comment by ewolfer67** [comment]
The attached image is the only asset.

**Comment by khattakdev** [comment]
Ah nvm, I thought you saying to make the button only clickable.
I'll take this issue.

**Comment by ewolfer67** [comment]
I can give you separate assets but I thought having the whole image "clickable" might be easier.

**Comment by khattakdev** [comment]
It has a button in the center, which will make the user think that only the button is clickable. Since that will not be the case, the user will be confused thinking the page has a bug.

**Comment by ewolfer67** [comment]
Here they are as two separate elements. Use the water as a background and float the PNG over the center as the clickable area.

![404jelly](https://user-images.githubusercontent.com/29734072/101994061-54b5b700-3c74-11eb-8e13-f8e25ab06051.png)
![404water](https://user-images.githubusercontent.com/29734072/101994062-57181100-3c74-11eb-85fb-c90efc513ee8.jpg)

**Comment by khattakdev** [comment]
@ericboucher The button should return the user to the home page or to the previous page?

**Comment by ericboucher** [comment]
@khattakdev let's go back to the `map` page :)

**Comment by khattakdev** [comment]
@ericboucher Not sure why you mentioned the `map` page specifically. 
Imagine if the user is on the `home` page and clicks on a broken link, he will be directed to the `map` page when he clicks on `Return to the Surface`. Isn't it better to always send him to the page from where he came?

**Comment by ericboucher** [comment]
@khattakdev yes if they come from a broken link within the app but that should hopefully be quite rare. The most likely scenario is that they come following an outdated link out there, or a link with a typo. So we could redirect to the previous page if it was on Aqualink, and otherwise go to the map. What do you think?

**Comment by khattakdev** [comment]
@ericboucher This might be kinda complex to achieve since JavaScript doesn't allow us to check the previous path due. 

One way to do this is to add the current Path to Router State when navigating, so when landed on the 404 pages, we can check the router state and make our decision based on that.

Another solution is to use `document.referrer` which gives you the page that linked to this page. But I found it behaving a little bit weird when I intentionally added a typo in the `to` field of **View The Map** and **Register Your Site** (Home Page buttons).

What do you think?
