### ISSUE TITLE
Improve timezone handling

### ISSUE THREAD

**Issue by ericboucher** [aqualinkorg/aqualink-app#384]
We display dates in the sites local timezone.

The dates are stored in the database in UTC. To achieve our goal, we currently convert all dates to string using their respective timezone but the timezone info gets "removed in the process.
Eg. `2020-12-06 12:00 UTC` becomes (in PST) `2020-12-06 04:00` without any timezone info.

Hence, we lose crucial information in the process. For example. running `new Date(transformedDate).toLocaleString(timezone)` does not work and shifts the time again as it wrongly assumes that the given date is in UTC.

Instead, we would like to keep the complete date object and simply shift the timezone it is displayed in.

Eg. `2020-12-06 12:00 UTC` should become (assuming the destination timezone is PST) `2020-12-06 04:00 PST`, as a date object (preferred), or a string.

**Comment by ericboucher** [comment]
Let's keep a normal datestring in UTC as long as we can and instead create a smart util function to localize the dates and times before we display them.

So instead, let's create one/two functions to use at the LAST moment to display dates, eg: displayTimeInTimezone and displayDateInTimezone following this logic:

const dateString = new Date(date).toLocaleString("en", {
    day: "2-digit",
    month: "2-digit",
    year: "2-digit",
    ...(hourlyData ? hourlyOptions : {}),
  });

  const timeZoneName = getTimeZoneName(timeZone || "UTC");

  return `${dateString}${hourlyData && timeZoneName && ` ${timeZoneName}`}

**Comment by tleraj** [comment]
@ericboucher  So the basic idea is that we hold the dates just as they come from the backend (in ISO format), and the whole timezone information gets attached right before we display them (e.g on chart tooltip, survey dates, ...).

**Comment by tleraj** [comment]
Also, I'm pretty sure that the warning in https://github.com/aqualinkorg/aqualink-app/issues/445 is caused by the fact that we use `moment` to display dates at any format we want. If we could make the convention that we would display dates in either of these formars:
 - `MM/DD/YY(YY)`
 - `MM/DD/YY(YY) HH:MM (AM or PM) {timeZoneName}`,

then we could use the function bellow for time display and give the the necessary arguments:

```typescript
export const displayTimeInLocalTimezone = (
  hourlyData: boolean,
  date: DateString,
  timeZone?: string | null,
  options?: Intl.DateTimeFormatOptions
) => {
  if (date) {
    const timeZoneName = getTimeZoneName(timeZone || "UTC");
    const dateString = new Date(date)
      .toLocaleString("en-US", {
        day: options?.day || "2-digit",
        month: options?.month || "2-digit",
        year: options?.year || "2-digit",
        ...(hourlyData
          ? {
              hour: options?.hour || "2-digit",
              minute: options?.minute || "2-digit",
            }
          : {}),
        timeZone: timeZone || "UTC",
      })
      .replace(",", "");

    return `${dateString} ${hourlyData && timeZoneName ? timeZoneName : ""}`;
  }
  return date;
};
```
