### ISSUE TITLE
Add exclusion date section for reef admins

### ISSUE THREAD

**Issue by ericboucher** [aqualinkorg/aqualink-app#387]
If there is a spotter, add a time selector on the right side with the following notice:
`Spotter data before this date will not be displayed`

<img width="1467" alt="Screen Shot 2020-12-16 at 9 43 22 AM" src="https://user-images.githubusercontent.com/16843267/102394179-38748b80-3f8e-11eb-8dfc-381ba60534a4.png">

- The time is selected in the site timezone (same as dive time)
- This should add an exclusion period of 1-month ending with this date

**Comment by ericboucher** [comment]
@avalmas-programize let's update the exclusion "date" paradigm to take times instead of just dates.

**Comment by avalmas-programize** [comment]
I have some questions:
- Does this mean that a spotter has a unique set of (start, end) dates?
- Should we add a relationship between the exclusionDates table and the reef table (we can keep the spotterId field)
- Should we check for datetimes now and not dates in all data? (live data, historical data etc)

**Comment by ericboucher** [comment]
- no it will still have multiple ones but the goal of this issue is to create the "initial" exclusion date and avoid getting data from installation


- I don't think we need a relationship between these two tables, we can just get the spotterId currently associated with the reef

- yes, as mentioned in my comment above we should check for datetime instead of dates

**Comment by ericboucher** [comment]
Implemented as a popup
