### ISSUE TITLE
Add update info to metric cards 

### ISSUE THREAD

**Issue by ericboucher** [aqualinkorg/aqualink-app#390]
We would like to make it clearer to users when the data was last updated.

For satellite data and DHW we should inform the user about the update frequency
For spotter, we should display the last data received time (eg. `data received 5min ago`)

  // Sofar variables used by Aqualink
  
  https://polar.ncep.noaa.gov/waves/
  SofarModels.NOAAOperationalWaveModel: {
    significantWaveHeight: 'significantWaveHeight',
    meanDirectionWindWaves: 'meanDirectionWindWaves',
    peakPeriod: 'peakPeriod',
  }
  
  SofarModels.NOAACoralReefWatch: {
    degreeHeatingWeek: 'degreeHeatingWeek',
    analysedSeaSurfaceTemperature: 'analysedSeaSurfaceTemperature',
  }

  SofarModels.GFS: {
    magnitude10MeterWind: 'magnitude10MeterWind',
    direction10MeterWind: 'direction10MeterWind',
  }
  
  
Designs to come soon - @drewjgray

**Comment by drewjgray** [comment]
@ericboucher What is the update frequency currently for the three data sources?

**Comment by drewjgray** [comment]
Here are the designs. The update frequencies are placeholders, we should double-check the data apis. 

<img width="576" alt="Screen Shot 2020-12-17 at 9 25 08 AM" src="https://user-images.githubusercontent.com/6283065/102512259-71c10000-404f-11eb-828f-8514da7ee90e.png">
<img width="576" alt="Screen Shot 2020-12-17 at 9 25 16 AM" src="https://user-images.githubusercontent.com/6283065/102512262-72599680-404f-11eb-926a-6548094b5e1a.png">
<img width="572" alt="Screen Shot 2020-12-17 at 9 25 24 AM" src="https://user-images.githubusercontent.com/6283065/102512265-72f22d00-404f-11eb-9e45-8bd0fc0513d6.png">
<img width="405" alt="Screen Shot 2020-12-17 at 9 36 36 AM" src="https://user-images.githubusercontent.com/6283065/102512266-72f22d00-404f-11eb-9069-b61f9f7b59c4.png">

**Comment by drewjgray** [comment]
@ericboucher notice I deleted the icons in the top right of the sat and buoy card and made the titles on one line.
