### ISSUE TITLE
Improve https://aqualink.org/register

### ISSUE THREAD

**Issue by ericboucher** [aqualinkorg/aqualink-app#396]
The site registration page is advertised on the home page and needs a bit of work. 

First, there is an unnecessary horizontal scroll on mobile.

Second, we need to make it clear that you first need to create an account before you can register a site. Let's add a message below the title of the form `Please sign up [here] before registering a new site`

**Comment by khattakdev** [comment]
I'll take this

**Comment by ericboucher** [comment]
@khattakdev let me know if you have any questions :)
