### ISSUE TITLE
Improve site search & click behavior

### ISSUE THREAD

**Issue by ericboucher** [aqualinkorg/aqualink-app#431]
Let's take the time to improve the overall behavior of the search and table click.

- After selecting a reef, clicking on it again in the table should re-open the popup if it was closed and re-zoom to its location

**Comment by tleraj** [comment]
One other issue I noticed is the following.

 - Search for a random location (e.g. `Sweden`)
 - The map centers to Sweden correctly
 - Then select an item from the search dropdown
 - The map does not center to that reef, but the table and the card work correctly
