### ISSUE TITLE
Restrict non reef admins from accessing buoy application data

### ISSUE THREAD

**Issue by tleraj** [aqualinkorg/aqualink-app#437]
Right now, any signed up user has access to a reef's application. We need to change this and only allow reef managers to be able to access a reef's application.

**Comment by avalmas-programize** [comment]
This is resolved by https://github.com/aqualinkorg/aqualink-app/pull/457
However we still have (for compatibility reasons) the old endpoint with which you can fetch any reef-application unrestricted (provided that you guess the hashed id or the uid correctly)
Anything else that should be done on this @ericboucher ?

**Comment by ericboucher** [comment]
I think we can probably remove the old endpoints then. I'll check with the team that they are not used anymore but if you can prepare a quick PR to remove them that would be great!
