### ISSUE TITLE
Add sensor date range

### ISSUE THREAD

**Issue by ericboucher** [aqualinkorg/aqualink-app#502]
Add the available sensor date range below the title in grey. (grey area only for now, no button needed)

![Screen Shot 2021-03-24 at 11 36 07 AM](https://user-images.githubusercontent.com/16843267/112585791-be874600-8db7-11eb-860f-ae9d25af4ea6.png)

**Comment by jrn2778** [comment]
Hello,

Can I take a shot at this? If so, can you lead me in the right direction as to where in the codebase I'll find where to add this / any other applicable resources?

Thank you!
