### ISSUE TITLE
Change map icons for sites with a buoy, and add HOBO icons for sites with a HOBO logger (icons attached)

### ISSUE THREAD

**Issue by drewjgray** [aqualinkorg/aqualink-app#511]
[icons.zip](https://github.com/aqualinkorg/aqualink-app/files/6252954/icons.zip)

Let's change the icons that we have in the app for sites that have a spotter and sites that have HOBO data.
- The new icons should still change color based on the the alert level
- Ideally, the spotter icon should be blinking (see below)

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue. Please guide me a bit more

**Comment by drewjgray** [comment]
The spotter icon should be blinking (see screen recording). The icons should have the white outline when selected. 

https://user-images.githubusercontent.com/6283065/113486412-60b5c680-9467-11eb-8ee8-7e9e54d79043.mov

**Comment by ericboucher** [comment]
Hi @himanshu007-creator please have a try yes!

As a first step you can look at how we get the current pins for the map through `findIntervalByLevel` in `website/src/helpers/bleachingAlertIntervals.ts`
