### ISSUE TITLE
Add detailed temperature chart for all sites

### ISSUE THREAD

**Issue by ericboucher** [aqualinkorg/aqualink-app#541]
We would like to change the site page by:
- Replace the featured image by the daily temperature chart, renamed "Heat Stress Analysis". Make it a bit similar to the screenshot below with the following changes:
	- only display the last 2 months of data
	- have the title a bit higher, aligned with LAT/LNG maybe?
<img width="1680" alt="Screen Shot 2021-04-28 at 12 21 19 PM" src="https://user-images.githubusercontent.com/16843267/116490106-6aa2cd80-a84b-11eb-8bec-3d027fc34f45.png">

- Display the detailed temperature chart for all sites, renamed "Temperature Analysis"
	- the title can be removed from the stats box
	- there should be at most 3 columns in the analysis box (SST is has the lowest priority)

**Comment by tleraj** [comment]
So for the temp analysis card, the priority is `spotter > hobo > sst`?

**Comment by tleraj** [comment]
Also, should the chart next to the map have a tooltip?
