### ISSUE TITLE
Firebase function fail   

### ISSUE THREAD

**Issue by avalmas-programize** [aqualinkorg/aqualink-app#557]
On Programize Staging
- Update daily data failed multiple times with error: `memory limit exceeded`
- SST time series update: `QueryFailedError: invalid input value for enum sources_type_enum: "noaa"`

On Staging:
- Update daily data failed multiple times with error: `memory limit exceeded`

On Production:
- SST time series update failed with error: `memory limit exceeded`

**Comment by ericboucher** [comment]
@avalmas-programize what solutions do you propose?
