### ISSUE TITLE
Add an endpoint to forward current data from Sofar Api

### ISSUE THREAD

**Issue by ericboucher** [aqualinkorg/aqualink-app#56]
We should add an endpoint to our API that is used to fetch the most up to date information about wind, waves and temperature to populate the reef detail page. When available, the data should come from the spotter.

In particular, this enpoint should return for a given reef:

- [x] satellite temp
- [x] surface temp (opt.)
- [x] bottom temp (opt.)

- [x] wind speed
- [x] wind direction
- [x] wave height
- [x] wave direction
- [x] wave period

<img width="882" alt="Screen Shot 2020-07-15 at 7 31 59 PM" src="https://user-images.githubusercontent.com/16843267/87619793-e2937300-c6d1-11ea-8b68-d7590239cf14.png">

**Comment by avalmas-programize** [comment]
https://github.com/aqualinkorg/aqualink-app/pull/227
