### ISSUE TITLE
Integrate OceanSense data and charts

### ISSUE THREAD

**Issue by ericboucher** [aqualinkorg/aqualink-app#562]
We would like to integrate new datasets coming from OceanSense and display it in new charts.

- The data will come directly from an external API
- Only a very small sample of reefs will be affected

![REEF DETAIL WITH OCEANSENSE_small](https://user-images.githubusercontent.com/16843267/120553943-f90bf100-c3ad-11eb-8fcf-2b3531e7a7cd.jpg)

**Comment by drewjgray** [comment]
Here are the 5 icons for acidity, conductivity, pressure, dissolved oxygen, and oxidation reduction potential. 

[icons.zip](https://github.com/aqualinkorg/aqualink-app/files/6591532/icons.zip)
