### ISSUE TITLE
Collection query gets blocked by uBlock Origin

### ISSUE THREAD

**Issue by ericboucher** [aqualinkorg/aqualink-app#564]
Collection query gets blocked by uBlock Origin.

A very annoying consequence of that is the failure of account creation when using uBlock with a network error. But the firebase user still gets created which then creates a mismatch within Firebase and the DB.

The failing query:

https://programize-dot-ocean-systems.uc.r.appspot.com/collections 

To reproduce, install uBlockOrigin and try to create an account on https://aqualink-app-programize.web.app/

**Comment by avalmas-programize** [comment]
I have reproduced the error
Fortunately it is just the GET collections/ request, so it doesn't affect the database integrity

It seems that the uBlock has a filter `appspot.com/collect` so it matches the our endpoint
![image](https://user-images.githubusercontent.com/69854742/121208663-e64c5d00-c882-11eb-91b2-eaa5b73f495c.png)

We can change the collection endpoint prefix
