### ISSUE TITLE
Make "Add Survey" text clickable

### ISSUE THREAD

**Issue by ericboucher** [aqualinkorg/aqualink-app#577]
<img width="1469" alt="Screen Shot 2021-06-30 at 6 18 16 PM" src="https://user-images.githubusercontent.com/16843267/123996439-2edbcf80-d984-11eb-934a-c2444b95e0ca.png">

**Comment by drewjgray** [comment]
The vertical alignment is slightly off - see screenshot attached. 
![Screen Shot 2021-07-06 at 5 12 53 AM](https://user-images.githubusercontent.com/6283065/124597915-e6576280-de18-11eb-91a1-a0ede417868b.png)
