### ISSUE TITLE
Heat Stress Tracker Dashboard

### ISSUE THREAD

**Issue by ericboucher** [aqualinkorg/aqualink-app#582]
Create a collection programmatically called "Heat Stress Tracker" that always fetches all the sites with a `DHW > 0`

Should we do this in the backend or in the frontend @avalmas-programize @tleraj ?

**Comment by avalmas-programize** [comment]
I think the best approach is from the backend.
Also this will be a dynamic dashboard, i.e. the user cannot add new reefs to it, as they are managed from the system.
For now we can get away with a fixed endpoint, for example `/collections/heat-stress-tracker`.
Any concerns for this @tleraj in the frontend?
