### ISSUE TITLE
Fix threshold text overlapping

### ISSUE THREAD

**Issue by drewjgray** [aqualinkorg/aqualink-app#593]
![Screen Shot 2021-07-06 at 11 51 47 AM](https://user-images.githubusercontent.com/6283065/124653256-ecb60080-de51-11eb-89f3-e218528d0215.png)
Move 'Bleaching Threshold' text to above the line, and move 'Historical Max' text to below the line. That way they are not overlapping. 
@ericboucher

**Comment by tleraj** [comment]
@drewjgray Even with this approach, there are cases that these two overlap. I thought of some approaches like the following:

![Screenshot_20210707_153220](https://user-images.githubusercontent.com/64922890/124760098-0e3de780-df39-11eb-8c55-5151d303d5d4.png)
![Screenshot_20210707_151529](https://user-images.githubusercontent.com/64922890/124760103-0f6f1480-df39-11eb-8cba-cf19b54cbe50.png)

Let me know what you think :slightly_smiling_face:
