### ISSUE TITLE
Fix alignment issues on stats card

### ISSUE THREAD

**Issue by drewjgray** [aqualinkorg/aqualink-app#594]
![Screen Shot 2021-07-06 at 12 04 58 PM](https://user-images.githubusercontent.com/6283065/124653646-6817b200-de52-11eb-876c-cba48c790910.png)

The stats card should be left-aligned. 
1) Align the "min, max, mean" text with the left side of the date heading.
2) Align the SST title with the left side of the SST temps. 
3) The Historic title and historic temps look good, and are left-aligned as they should, but make sure it is not just a coincidence. 
@ericboucher

**Comment by ericboucher** [comment]
@tleraj let's fix that in the #565 PR.
