### ISSUE TITLE
Images not loaded at `/tracker` page

### ISSUE THREAD

**Issue by tleraj** [aqualinkorg/aqualink-app#606]
When we visit the `/tracker` page, the images are sometimes not loaded correctly. Probably it has to do with the way we acquire the images aspect ratios.

Example [here](https://aqualink-app-programize.web.app/map).
The deployed branch is `improve-map-performance`.

**Comment by tleraj** [comment]
@Ry-DS I think I fixed it by https://github.com/aqualinkorg/aqualink-app/pull/601/commits/ddd7ec6ad782a8a720530640d02124945536715e. Please take a look and let me know what you think.
Deployed on https://aqualink-app-programize.web.app/ :wink:

**Comment by Ry-DS** [comment]
Solved in #601
