### ISSUE TITLE
Adding exclusion period should delete data

### ISSUE THREAD

**Issue by ericboucher** [aqualinkorg/aqualink-app#628]
As a site admin, when I add an exclusion date, I would like to see it affect the charts.

In other words, the corresponding data should be filtered out from the time_series table or deleted.

**Comment by ericboucher** [comment]
@imskr thanks for proposing your help!

**Comment by imskr** [comment]
Thanks @ericboucher

**Comment by imskr** [comment]
@ericboucher while setting up the project locally and running `yarn start` i'm getting following error:

```
➜ yarn start
yarn run v1.22.11
$ lerna run start -- --parallel
lerna notice cli v3.22.1
lerna info versioning independent
lerna info Executing command in 2 packages: "yarn run start --parallel"
lerna ERR! yarn run start --parallel exited 1 in 'api'
lerna ERR! yarn run start --parallel stdout:
$ yarn run start:prod --parallel
$ node dist/src/main.js --parallel
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run start --parallel stderr:
/home/skr/Github/aqualink-app/node_modules/multer-google-storage/lib/index.js:48
            throw new Error('You have to specify bucket for Google Cloud Storage to work.');
            ^

Error: You have to specify bucket for Google Cloud Storage to work.
```

Do I have to setup GCP to get this running locally?

**Comment by ericboucher** [comment]
Hmm, good catch @imskr, let me add a quick fix for that!

**Comment by imskr** [comment]
Thanks @ericboucher

**Comment by imskr** [comment]
@ericboucher I'm still getting the same error on 1dev-no-upload` branch

**Comment by ericboucher** [comment]
@imskr have you tried the updated master branch? It should work find but let me know if it doesn't and we can investigate :)
