### ISSUE TITLE
Clean up charts logic

### ISSUE THREAD

**Issue by tleraj** [aqualinkorg/aqualink-app#678]
Since we now only use time-series data, we need a more compact way for processing/displaying chart data. Right now, we are passing each metric and we calculate chart properties (like axis limits) based on some specific metrics. The goal is to pass an array of datasets, where a dataset could look like

```typescript
  data: SofarValue[];
  unit?: string;
  color: string;
  label: string;
```

and process/display them with a simple `map`. This means that we treat each dataset in the same way, and as a result, the code complexity will be reduced a lot.

**Comment by ericboucher** [comment]
While we are at it, we should probably consider SofarValue to something more general, since not all. of our data comes from Sofra now
