### ISSUE TITLE
Give a better error when the backend fails to respond.

### ISSUE THREAD

**Issue by Ry-DS** [aqualinkorg/aqualink-app#700]
Currently if the backend is down, the website loads forever:
![image](https://user-images.githubusercontent.com/25571542/160774221-ccedc703-7035-4046-8e3e-4c05eba5e641.png)
![image](https://user-images.githubusercontent.com/25571542/160774285-be981f54-32f6-4d22-82ba-e388ec9754ac.png)

We should instead give a warning error or modal.

**Comment by echaidemenos** [comment]
I believe that was fixed down the road
![Screenshot from 2022-06-02 16-15-40](https://user-images.githubusercontent.com/80451946/171637756-32583bf9-b038-4d74-9590-62ae917687c5.png)
![Screenshot from 2022-06-02 16-16-01](https://user-images.githubusercontent.com/80451946/171637767-a1b08fac-58d3-4c05-a896-a0db01bf5006.png)

**Comment by ericboucher** [comment]
Thanks @echaidemenos, let's close it then.
