### ISSUE TITLE
Loading site page is slow

### ISSUE THREAD

**Issue by ericboucher** [aqualinkorg/aqualink-app#703]
Let's understand which queries are taking too long and optimize our API calls accordingly.

Especially if the data we are waiting for is not necessary to start rendering.

**Comment by echaidemenos** [comment]
The app, groups multiple request and waits them all to start rendering. One of them is `livedata` taking most of the time, because it makes multiple requests to an external API. I will de-group it since its only a small part of the data shown and it will load separately
