### ISSUE TITLE
Do not fetch liveData for the featured site?

### ISSUE THREAD

**Issue by ericboucher** [aqualinkorg/aqualink-app#710]
I do not think we need the liveData for the featured site, but we are still loading it and waiting for it to display the card.

**Comment by ericboucher** [comment]
Note that this will be less of a concern once #708 is merged since the queries will be de-coupled

**Comment by ericboucher** [comment]
Looking at the requests when loaidng a site, it seems that we are sending multiple overlapping queries. Let's look into how we can optimize that.

<img width="664" alt="Screen Shot 2022-05-11 at 4 43 09 PM" src="https://user-images.githubusercontent.com/16843267/167944314-dfcd4cf1-2c74-4b33-938e-ddec520df375.png">

**Comment by echaidemenos** [comment]
how often we do update our latest_data table? If we update it often enough we could: 
- have an endpoint for spotter location (the only live data we currently use)
-  determine if we have spotter data by checking `latestData.topTemperature` timestamp (like we do here `const hasSpotterData = Boolean(liveData?.topTemperature);`) 
- and remove the `live_data` endpoint.

**Comment by ericboucher** [comment]
1. My main problem here is that we seem to be requesting the same data multiple times, suggesting that different components request the same data, which could be optimized
2. Specifically, the featured site component on this page https://aqualink.org/map does not require liveData, since, as you pointed out, the only info we don't have is the spotter position, and we are not using it on this page :)
