### ISSUE TITLE
Use Sofar newly available wind velocity and direction variables

### ISSUE THREAD

**Issue by ericboucher** [aqualinkorg/aqualink-app#724]
It looks like Sofar made wind velocity and direction available directly through their API. Let's update our code to leverage these variables directly instead of re-calculating them on our end. https://docs.sofarocean.com/marine-weather

**Comment by echaidemenos** [comment]
cannot find success with `https://api.sofarocean.com/marine-weather/v1/models/GFS/forecast/point?longitude=-152.0001&latitude=37.0001&variableIDs=magnitude10MeterWind&token=OUR_TOKEN_HERE` or `https://api.sofarocean.com/marine-weather/v1/models/GFS/forecast/point?longitude=-152.0001&latitude=37.0001&variableIDs=GFS-magnitude10MeterWind&token=OUR_TOKEN_HERE`. maybe they have not activated it yet?

**Comment by ericboucher** [comment]
@evanShap any thoughts? We were looking at https://docs.sofarocean.com/marine-weather and hoping to use magnitude and direction directly

**Comment by ericboucher** [comment]
My mistake, the docs are not up to date. Closing as "wont fix"
