### ISSUE TITLE
Update FAQ

### ISSUE THREAD

**Issue by ericboucher** [aqualinkorg/aqualink-app#778]
Update the FAQ page with the latest information available in https://docs.google.com/document/d/1rBEEA9V2JwKmMHPB9-LAfwm26MHmxijT96iELae60dw/

**Comment by alifaroo-q** [comment]
Hi, I would like to take this issue. Can you point out where the FAQ file is I can't seem to find it?

**Comment by christophermorin** [comment]
Hey @alifaroo-q , if you need to find a specific file on a repo the 'go to file' button on the repos main page will help. In this case you would click 'go to file' and then type in 'faq' in the search field. 

@ericboucher There are a few questions in the current FAQ that are not in the updated list, do you want these removed in the new version or kept and any new questions in the link provided added around them?
