### ISSUE TITLE
Add barometric data

### ISSUE THREAD

**Issue by ericboucher** [aqualinkorg/aqualink-app#779]
Add barometric data available with new smart buoys and display data in the temp card

note - use the same font as temp data
![BAROMETRIC PRESSURE (1)](https://user-images.githubusercontent.com/16843267/190602204-990c1ee9-7ea4-4309-9919-53433c047884.png)

**Comment by knownasaritra** [comment]
can I work on this

**Comment by ericboucher** [comment]
Hi @ak090498 unfortunately this task was assigned to @echaidemenos.
We would love to get your help on other tasks! Feel free to send me an email at eric@ovio.org with a few tasks you would be interested in helping with :)
