### ISSUE TITLE
Implement new table designs for mobile

### ISSUE THREAD

**Issue by ericboucher** [aqualinkorg/aqualink-app#78]
Implement mobile designs for the home page and make the app mobile friendly

![image](https://user-images.githubusercontent.com/16843267/90683949-35ee6900-e21c-11ea-85a0-65451650589f.png)

![image (1)](https://user-images.githubusercontent.com/16843267/90683959-3981f000-e21c-11ea-91a6-b90cb66ddba5.png)

**Comment by SimplyBallistic** [comment]
Where are we at currently with this issue? Is the last step to make the table look more like what's in the screenshots?

**Comment by SimplyBallistic** [comment]
* working on restyling the table to fit the given mockup
