### ISSUE TITLE
Display temperature data consistently on survey details page

### ISSUE THREAD

**Issue by ericboucher** [aqualinkorg/aqualink-app#785]
At the moment, satellite temp data is not showing consistently on the survey details page, which should be fixed.
In addition, we would like to display spotter temp data as well, when available.

Here is a good site to take as an example https://aqualink.org/sites/2943 and a survey with no temp value: https://aqualink.org/sites/2943/survey_details/401

**Comment by ak090498** [comment]
@ericboucher Will work on this

**Comment by ericboucher** [comment]
Thanks @ak090498 for proposing your help. Please go ahead. Let me know if you have questions.

**Comment by ak090498** [comment]
Unfortunately I am a bit busy and cannot work on this as of now , really sorry
