### ISSUE TITLE
Analyze dashboard activity

### ISSUE THREAD

**Issue by Caesarh97** [aqualinkorg/aqualink-app#934]
Aqualink has had a free data pool for all the spotters that have now been used up. We now pay monthly for the data if a buoy transmits one or more data points in a month. We’d like to know if the buoy managers are using their Aqualink dashboard. Buoys that transmit data can be marked as "deployed", "maintenance", or "shipped" in Internal. Any other status should not transmit any data. 

We want to see how many times the dashboard is being accessed for the spotters we’re paying for. 

Site visits are the most important to track. Both the number of sessions and users would be beneficial. If it's possible to track the activity of the user/s added as buoy manager in Internal, that would be great as well. 

Surveys or uploaded data would be interesting, but this is not a requirement. 

**Update from Pete**
"Just a database log showing the time stamp of when the site was accessed and the userid if they’re logged in should be enough"

**Comment by Caesarh97** [comment]
If it would be possible to see how many times data is being downloaded from a dashboard, that would be great! This is not a requirement, though.

**Comment by echaidemenos** [comment]
Hello @Caesarh97! In the PR, it is possible to query, using the api,  `time_series_request` which in practice is how many times the dashboard is visited and `csv_download` which counts the times data are downloaded. You mean to see these information throw the UI?

**Comment by Caesarh97** [comment]
Hello @echaidemenos! Awesome! I think it would be ideal if Aqualink super admins and the site owner could see that information only. Please let me know if it would be significantly easier to display it publically or just for Aqualink in Internal, for example. If not, I think it would be better if the site manager and super admins could see the stats.
