### ISSUE TITLE
Add sites with live streams to the map

### ISSUE THREAD

**Issue by Caesarh97** [aqualinkorg/aqualink-app#973]
We would like to add all of the sites with live streams to the map. The idea is that we'll have a button that filters out the sites to only those with live streams connected to them. If you have an idea of how to automatically populate this filter by which sites have a live stream connected to it, we can do so. If manually populating the list of sites with a live stream is easier, I can do that whenever we need to add or remove sites. The sites that have live streams are:

1. 3205
2. 3492
3. 2904
4. 3301
5. 1006
6. 3358
7. 1024
8. 3026

The name of the filter button can be "Sites with live streams only".

**Extra:** Depending on how easy it would be to simultaneously add a third filter button, we could add a button for 3D models. Pete and I have yet to discuss this, however. The sites that have 3D models are:

1. 1006
2. 3319
3. 3323
4. 3320
5. 3322
6. 3321
7. 3207

The name of the filter button can be "Sites with 3D models only".

![Sites with live streams only 1](https://github.com/aqualinkorg/aqualink-app/assets/113801743/57282cc5-a07a-4f8b-a5ad-c8ee1b341432)
![Sites with live streams only](https://github.com/aqualinkorg/aqualink-app/assets/113801743/6fc55182-1767-44a2-ac16-e3a4950c2f02)

**Comment by ericboucher** [comment]
@Caesarh97 maybe we could use a dropdown for the 3 filters?
