### ISSUE TITLE
ASL Environmental Sciences - Embed iframe with data to Aqualink dashboards

### ISSUE THREAD

**Issue by Caesarh97** [aqualinkorg/aqualink-app#975]
Hello, 

Peter Willis from ASL Environmental Sciences Inc. has contacted us about uploading their data to Aqualink. The idea is that the data would be processed off-site since it seems to be complicated. The processed data will then be displayed in an iframe which will be embedded into the Aqaulink dashboard. If I remember correctly, Peter Willis will create the iframe. 

The ask for this project is for Eric and the Ovio team to create a section on ASL Environmental Sciences' Aqualink dashboards where we will display their iframe. Peter Willis also asked if we could share CSS codes with him so he can style the content in the iframe to our "Aqualink style". Eric and the Ovio team will likely have to give Peter Willis some advice along the way. 

**Info about the product/project:** They have a complete product called Acoustic Zooplankton Fish Profiler (AZFP), but they are creating a new product called AZFP Nano, which they will use with the Bristlemouth connection as well. They want to display the AZFP Nano version on Aqualink. They expect around 60-90 of the Nano versions to be used, and each would need an Aqualink site. They expect the AZFP Nano to be completed mid to late summer. After that, they will begin product testing. They would like to use us to present their data effectively.

Below is the email from Peter Willis after our meeting showing what the data he wants to add in an iframe could look like:

Here is the mockup of the ASL data-table/file-list as discussed in the meeting. (Attached image)

The visualization is meant only to show what type of tabular data we hope to present.
The formatting may be changed to suit the style of the Aqualink data site.

![ASL_Aqualink_iFrame_mockup](https://github.com/aqualinkorg/aqualink-app/assets/113801743/d6170ac2-3e81-4d83-b173-f040a809d7a3)

Comment: The iframe is something that we could reuse for other users if they want to display any additional information that Aqualink doesn't offer. I can't think of any other cases where we could use an iframe right now, but they may come up in the future.

**Comment by ericboucher** [comment]
@echaidemenos let's create a new column on the sites table `iframe_link` and create a space to display on the site page between charts and the survey history
