### ISSUE TITLE
Fix ghost hover points and upgrade Chartjs

### ISSUE THREAD

**Issue by Caesarh97** [aqualinkorg/aqualink-app#994]
There's an issue when you hover over the graphs on the dashboard. It works great until you hover over the circle that indicates a survey was conducted at that point in time. You can look at this site as an example. [https://aqualink.org/sites/3331](https://aqualink.org/sites/3331)

https://github.com/aqualinkorg/aqualink-app/assets/113801743/4fd9c60c-640f-44f0-83f5-bb73d7d5a3a8

**Comment by Caesarh97** [comment]
Hi @ericboucher and @echaidemenos, I just wanted to share that I ran into two issues with the circle again. The sensitivity has worked great otherwise, and there's a good "feel" to it! 

In this video, you can see how multiple circles appear and jump back and forth. This appears on all sites with buoy data.
https://github.com/aqualinkorg/aqualink-app/assets/113801743/b9c430fa-5cc5-49ae-a446-f33c11d18181

In this video, you can see how the circles get stuck. They only disappear if you reload the page. This happens for all the sites with HOBO data. 
https://github.com/aqualinkorg/aqualink-app/assets/113801743/fa8f050e-833a-442a-803f-2afb0cc97fb5

**Comment by yaodingyd** [comment]
I'm trying to reproduce this locally and I think I'll need a SOFAR API key to generate a chart to work with. Any idea how can I get such a key? the website https://www.sofarocean.com/ is not very helpful

**Comment by ericboucher** [comment]
Hi @yaodingyd thanks for looking into this and sorry for the late reply. You should be able to connect directly to our backend API by using this env variable: `REACT_APP_API_BASE_URL=https://ocean-systems.uc.r.appspot.com/api` when running `yarn start` so that you can have the same data for site 3331
